---
- name: Add nginx repository
  yum_repository:
    name: nginx
    description: nginx repository
    baseurl: https://nginx.org/packages/rhel/$releasever/$basearch/
    gpgcheck: no
    enabled: yes
- name: Install nginx
  package:
    name: nginx
    update_cache: yes
- name: Enable nginx
  service:
    name: nginx.service
    state: started
    enabled: yes
- name: Copy index.html
  copy:
    src: ../../../../web/index.html
    dest: /usr/share/nginx/html/index.html
  notify: restart nginx
- name: Copy static assets
  copy:
    src: ../../../../web/assets/
    dest: /usr/share/nginx/html/assets/
  notify: restart nginx
- name: Add firewall ports
  ansible.posix.firewalld:
    zone: public
    service: http
    permanent: yes
    immediate: yes
    state: enabled
